# Generated by Django 4.1.5 on 2023-01-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('firstName', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('dateOfBirth', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ClubReps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repNumber', models.PositiveBigIntegerField()),
                ('clubPassword', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmTitle', models.CharField(max_length=300)),
                ('ageRating', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('filmImages', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubName', models.CharField(max_length=300)),
                ('street', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('postCode', models.CharField(max_length=10)),
                ('landLineNumber', models.CharField(max_length=30)),
                ('mobilePhoneNumber', models.CharField(max_length=30)),
                ('clubEmailAddress', models.CharField(max_length=100)),
                ('clubRepID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='UWEFlix.clubreps')),
            ],
        ),
    ]
