# Generated by Django 4.1.5 on 2023-01-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0002_accounts_clubreps_films_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='filmImages',
            field=models.ImageField(blank=True, null=True, upload_to='UWEFlix/media/images/'),
        ),
    ]
