# Generated by Django 4.1.5 on 2023-01-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0004_alter_films_filmimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='filmImages',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
