# Generated by Django 4.1.5 on 2023-01-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0005_alter_films_filmimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='description',
            field=models.TextField(),
        ),
    ]
